CXX = g++
CXXFLAGS = -g -Wall -Wextra -Wpedantic

.PHONY: all clean
all: program

program: romandigitconverter.o numberconversion.o
	$(CXX) $(CXXFLAGS) -o program numberconversion.o romandigitconverter.o

romandigitconverter.o: romandigitconverter.cpp
	$(CXX) $(CXXFLAGS) -c romandigitconverter.cpp

numberconversion.o: numberconversion.cpp numberconversion.h
	$(CXX) $(CXXFLAGS) -c numberconversion.cpp

.PHONY : clean
clean:
	$(RM) *.o
	$(RM) program

